parameters:
    hgabka_kunstmaan_extension.max_page_insertion_depth: 3

services:
    hgabka_kunstmaan_extension.page_insert.twig.extension:
        class: Hgabka\KunstmaanExtensionBundle\Twig\Extension\PageInsertTwigExtension
        arguments:
            - "@doctrine"
            - "@kunstmaan_pageparts.twig.extension"
            - "%hgabka_kunstmaan_extension.max_page_insertion_depth%"
        tags:
            - { name: twig.extension }

    hgabka_kunstmaan_extension.page_insert.admin_form_type:
        class: Hgabka\KunstmaanExtensionBundle\Form\PageParts\InsertPagePagePartAdminType
        arguments:
            - "@request_stack"
            - "@doctrine"
            - "@kunstmaan_page_part.page_part_configuration_reader"
        tags:
            - { name: form.type, alias: page_insert_page_part_type }

    hgabka_kunstmaan_extension.settings_menu_adaptor:
        class: Hgabka\KunstmaanExtensionBundle\Helper\Menu\SettingsMenuAdaptor
        tags:
            -  { name: 'kunstmaan_admin.menu.adaptor' }

    hgabka_kunstmaan_extension.cache_manager:
        class: Hgabka\KunstmaanExtensionBundle\HttpCache\Manager
        arguments:
            - "%kernel.cache_dir%"
            - "@filesystem"
            - "@?fos_http_cache.cache_manager"

    hgabka_kunstmaan_extension.cache_purge_subscriber:
        class: Hgabka\KunstmaanExtensionBundle\EventListener\CachePurgeSubscriber
        lazy: true
        arguments:
            - "@hgabka_kunstmaan_extension.cache_manager"
            - "@?session"
        tags:
            - { name: doctrine.event_subscriber }

    # Optimalizálás végett adjuk át a container-t!
    hgabka_kunstmaan_extension.search_subscriber:
        class: Hgabka\KunstmaanExtensionBundle\EventListener\SearchSubscriber
        arguments:
            - "@service_container"
        tags:
            - { name: doctrine.event_subscriber }

    hgabka_kunstmaan_extension.searchable_entity_configuration:
        class: Hgabka\KunstmaanExtensionBundle\Configuration\SearchableEntityConfiguration
        lazy:  true
        arguments:
            - '%kunstmaan_node_search.indexname%' # direkt használjuk ugyanazt, mint a NodeSearch! Különben nem találja a normál keresés.
            - '%kunstmaan_node_search.indextype%' # direkt használjuk ugyanazt, mint a NodeSearch! Különben nem találja a normál keresés.
            - '@kunstmaan_search.search'
            - '@kunstmaan_admin.domain_configuration'
            - '%analyzer_languages%'
            - '@doctrine'
            - '@event_dispatcher'
        tags:
            - { name: kunstmaan_search.search_configuration, alias: Entity }

    hgabka_kunstmaan_extension.search.twig.extension:
        class: Hgabka\KunstmaanExtensionBundle\Twig\Extension\SearchTwigExtension
        arguments:
            - "@twig.extension.routing"
        tags:
            - { name: twig.extension }

    hgabka_kunstmaan_extension.user_edit:
        class: Hgabka\KunstmaanExtensionBundle\User\UserEditService
        arguments:
          - "@doctrine"
          - "@security.password_encoder"

    hgabka_kunstmaan_extension.form.type.autocomplete_entity_type:
        class: Hgabka\KunstmaanExtensionBundle\Form\Type\EntityAutocompleteType
        arguments:  ['@doctrine']
        tags:
            - { name: form.type }

    hgabka_kunstmaan_extension.form.type.plain_widget:
        class: Hgabka\KunstmaanExtensionBundle\Form\Type\StaticControlType
        tags:
            - { name: form.type }

    hgabka_kunstmaan_extension.form.help_type_extension:
        class: Hgabka\KunstmaanExtensionBundle\Form\Extension\HelpTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    hgabka_kunstmaan_extension.kuma_utils:
        class: Hgabka\KunstmaanExtensionBundle\Helper\KumaUtils
        arguments:  ["@doctrine", "@kunstmaan_admin.domain_configuration", "@request_stack", "@kunstmaan_media.media_manager", "@router", "%kernel.project_dir%"]

    hgabka_kunstmaan_extension.number_to_text:
        class: Hgabka\KunstmaanExtensionBundle\Helper\Number\NumberToText

    hgabka_kunstmaan_extension.fill_filter:
        class: Hgabka\KunstmaanExtensionBundle\Imagine\Filter\Loader\FillFilterLoader
        tags:
            - { name: "liip_imagine.filter.loader", loader: hg_fill }

    hgabka_kunstmaan_extension.fit_filter:
        class: Hgabka\KunstmaanExtensionBundle\Imagine\Filter\Loader\FitFilterLoader
        arguments: ["@liip_imagine"]
        tags:
            - { name: "liip_imagine.filter.loader", loader: hg_fit }

    hgabka_kunstmaan_extension.paste_filter:
        class: Hgabka\KunstmaanExtensionBundle\Imagine\Filter\Loader\PasteFilterLoader
        arguments: ["@liip_imagine"]
        tags:
            - { name: "liip_imagine.filter.loader", loader: hg_paste }

    hgabka_kunstmaan_extension.form.recaptcha_type:
        class: Hgabka\KunstmaanExtensionBundle\Form\Type\RecaptchaType
        arguments: ['']
        tags:
            - { name: form.type }

    hgabka_kunstmaan_extension.form.recaptcha_admin_type:
        class: Hgabka\KunstmaanExtensionBundle\Form\PageParts\RecaptchaPagePartAdminType
        arguments: ['']
        tags:
            - { name: form.type }

    hgabka_kunstmaan_extension.validator.recaptcha:
        class: Hgabka\KunstmaanExtensionBundle\Validator\Constraints\RecaptchaValidator
        arguments: ["@request_stack", "@hgabka_kunstmaan_extension.kuma_utils", '']
        tags:
            - { name: validator.constraint_validator }

    hgabka_kunstmaan_extension.recaptcha.subscriber:
        class: Hgabka\KunstmaanExtensionBundle\EventListener\RecaptchaEventSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }
